//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This Field Should not be Empty")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This Field Should not be Empty")]
        public double Price { get; set; }

        [Required(ErrorMessage = "This Field Should not be Empty")]
        public string Picture { get; set; }
    }
}
